### ISSUE TITLE
/OffensiveNim/src/clr_host_cpp_embed_bin.nim(28, 12) Error: Must be compiled in cpp mode

### ISSUE THREAD

**Issue by evandrix** [byt3bl33d3r/OffensiveNim#12]
on MacOS 10.15.7

**Comment by evandrix** [comment]
resolved by added `-b=cpp` to Makefile @ https://github.com/byt3bl33d3r/OffensiveNim/blob/master/Makefile#L6

according to https://nim-lang.org/docs/nimc.html
> -b, --backend:c|cpp|js|objc sets backend to use with commands like `nim doc` or `nim r`

**Comment by Neo23x0** [comment]
Thanks a lot. I stumbled over the same problem.
