### ISSUE TITLE
Load (0x80131604) [CLRError]

### ISSUE THREAD

**Issue by s1im3r00** [byt3bl33d3r/OffensiveNim#28]
C:\Users\Administrator\Downloads\nim-1.4.4\OffensiveNim-master\src\execute_assembly_bin.nim(15) execute_assembly_bin
C:\Users\Administrator\.nimble\pkgs\winim-3.6.0\winim\clr.nim(648) load
C:\Users\Administrator\.nimble\pkgs\winim-3.6.0\winim\clr.nim(322) invoke
C:\Users\Administrator\.nimble\pkgs\winim-3.6.0\winim\clr.nim(273) invoke
C:\Users\Administrator\.nimble\pkgs\winim-3.6.0\winim\clr.nim(208) clrError
Error: unhandled exception: unable to invoke specified member: Load (0x80131604) [CLRError]

**Comment by byt3bl33d3r** [comment]
I'm going to assume you're trying to load an Assembly that's signatured by AMSI.... if that's not the case i'm going to need a lot more info like what are you trying to run & from where?

Since this isn't an issue, i'm closing it but feel free to respond below.
