### ISSUE TITLE
minidump access denied

### ISSUE THREAD

**Issue by Fccarry** [byt3bl33d3r/OffensiveNim#32]
![image](https://user-images.githubusercontent.com/42264662/118612277-31c59b00-b7f0-11eb-93aa-8d35dc37dfc5.png)

**Comment by rafale0n** [comment]
That's because Administrator on the latest Windows 10 does not have debug privileges. Try to steal token from with the code in the contribution section example and re run to see if it works.

**Comment by byt3bl33d3r** [comment]
You need to run the executable as administrator in order to dump LSASS....
