### ISSUE TITLE
Making scripts more reusable

### ISSUE THREAD

**Issue by antemasqued** [byt3bl33d3r/OffensiveNim#54]
Hey @byt3bl33d3r, I know it's a small change, but would you be open to capitolizing and standardizing areas for text replacement? Atm I think we use a bunch of different placeholders for environment specific variables and files. Would you find it helpful if I submitted a PR replacing all that text with "`YOURDOMAIN`", "`PAYLOAD`" and whatnot? Not trying to step on anyone's toes here.

**Comment by byt3bl33d3r** [comment]
I'd be open to it if the scripts would still be able to work without needing to replace the variables
